let guest1 = ['Ali', 'Sameer', 'Irfan'];
guest1.unshift('Hamza');
guest1.splice(3, 0, 'Adeel');
guest1.push('Rehan');
console.log(`Dear ${guest1[0]}, I have invited you to dinner.`);
console.log(`Dear ${guest1[1]}, I have invited you to dinner.`);
console.log(`Dear ${guest1[2]}, I have invited you to dinner.`);
console.log(`Dear ${guest1[3]}, I have invited you to dinner.`);
console.log(`Dear ${guest1[4]}, I have invited you to dinner.`);
console.log(`Dear ${guest1[5]}, I have invited you to dinner.`);
console.log(`sorry, the table can't reach in time so I have only space for two people`);
let x = guest1.pop();
console.log(`${x}, sorry I can't invite you to dinner`);
let x1 = guest1.pop();
console.log(`${x1}, sorry I can't invite you to dinner`);
let x2 = guest1.pop();
console.log(`${x2}, sorry I can't invite you to dinner`);
let x3 = guest1.pop();
console.log(`${x3}, sorry I can't invite you to dinner`);
console.log(`${guest1[0]}, you are still invited.`);
console.log(`${guest1[1]}, you are still invited.`);
guest1.pop();
guest1.pop();
console.log(guest1);