let string = "ferarri";
console.log("is string == ferarri? | predict true");
console.log(string == "ferarri");
let string1 = "car";
console.log("is string1 == ferarri? | predict false");
console.log(string1 == "ferarri");
let string2 = "car";
console.log("is string2 !== car? | predict false");
console.log(string2 !== "car");
let string3 = "car";
console.log("is string3 !== ferarri? | predict true");
console.log(string3 !== "ferarri");

function lowerCase(str: string): boolean {
  return str === str.toLowerCase();
}
let string4 = "hello";
let string5 = "Hello";
console.log("is string4 is lower case? | expecter: true");
console.log(lowerCase(string4));
console.log("is string5 is lower case? | expecter: false");
console.log(lowerCase(string5));
let x = 5;
let y = 7;
console.log("is x equals y | expected : false");
console.log(x == y);
let x1 = 5;
let y1 = 5;
console.log("is x1 equals y1 | expected : true");
console.log(x1 == y1);
let x2 = 5;
let y2 = 7;
console.log("is x2 equals y2 | expected : true");
console.log(x2 !== y2);
let x3 = 5;
let y3 = 5;
console.log("is x3 equals y3 | expected : false");
console.log(x3 !== y3);
let x4 = 5;
let y4 = 7;
console.log("is x4 greater than y4 | expected : false");
console.log(x4 > y4);
let x5 = 9;
let y5 = 5;
console.log("is x5 greater than y5 | expected : true");
console.log(x5 > y5);
let x6 = 5;
let y6 = 7;
console.log("is x6 less than y6 | expected : true");
console.log(x6 < y6);
let x7 = 9;
let y7 = 5;
console.log("is x7 less than y7 | expected : false");
console.log(x7 < y7);
let x8 = 5;
let y8 = 7;
console.log("is x8 greater than or equal to y8 | expected : false");
console.log(x8 >= y8);
let x9 = 5;
let y9 = 5;
console.log("is x9 greater than or equal to y9 | expected : true");
console.log(x9 >= y9);
let x10 = 5;
let y10 = 7;
console.log("is x10 less than or equal to y10 | expected : true");
console.log(x10 <= y10);
let x11 = 9;
let y11 = 5;
console.log("is x11 less than or equal to y11 | expected : false");
console.log(x11 <= y11);
let x12 = 5;
let y12 = 5;
console.log('is x12 equals 5 AND y12 equals 5 | expected : true');
console.log(x12 == 5 && y12 == 5);
let x13 = 6;
let y13 = 5;
console.log('is x13 equals 5 AND y13 equals 5 | expected : false');
console.log(x13 == 5 && y13 == 5);
let x14 = 5;
let y14 = 5;
console.log('is x14 equals 5 OR y14 equals 5 | expected : true');
console.log(x14 == 5 || y14 == 5);
let x15 = 6;
let y15 = 9;
console.log('is x15 equals 5 OR y15 equals 5 | expected : false');
console.log(x15 == 5 || y15 == 5);
let array = [1,3,2,4,5,6,7,8];
console.log('is 9 is in array | predicted : false');
console.log(array.includes(9));
console.log('is 3 is in array | predicted : true');
console.log(array.includes(3));
console.log('is 9 is not in array | predicted : true');
console.log(!array.includes(9));
console.log('is 3 is not in array | predicted : false');
console.log(!array.includes(3));
