"use strict";
let guest = ['Ali', 'Amir', 'Irfan'];
console.log(`Dear ${guest[0]}, I have invited you to dinner.`);
console.log(`Dear ${guest[1]}, I have invited you to dinner.`);
console.log(`Dear ${guest[2]}, I have invited you to dinner.`);
console.log(`${guest[1]} can't make the dinner.`);
let guest1 = ['Ali', 'Sameer', 'Irfan'];
console.log(`Dear ${guest1[0]}, I have invited you to dinner.`);
console.log(`Dear ${guest1[1]}, I have invited you to dinner.`);
console.log(`Dear ${guest1[2]}, I have invited you to dinner.`);
