"use strict";
let names = ['Sameer', 'Abdullah', 'Fakhir', 'Muaaz', 'Umer'];
console.log('an index error in line no 2');
console.log(`Hey ${names[0]}, have you completed your task?`);
console.log(`Hey ${names[-1]}, have you completed your task?`);
console.log(`Hey ${names[2]}, have you completed your task?`);
console.log(`Hey ${names[3]}, have you completed your task?`);
console.log(`Hey ${names[4]}, have you completed your task?`);
console.log('after fixing the error');
console.log(`Hey ${names[0]}, have you completed your task?`);
console.log(`Hey ${names[1]}, have you completed your task?`);
console.log(`Hey ${names[2]}, have you completed your task?`);
console.log(`Hey ${names[3]}, have you completed your task?`);
console.log(`Hey ${names[4]}, have you completed your task?`);
